### ISSUE TITLE
1장 깨끗한 코드

### ISSUE THREAD

**Issue by YHLEE9753** [Dev-Prison/Clean-Code#1]

**Comment by ynoolee** [comment]
API 에 대한 응답 역할을 하는 DTO 네이밍은 어떻게 하는 것이 적절 할까요?

만약 다음과 같은 경우가 있다고 한다면 
1) 게시글에 대한 단일 요청 
2) 최신 게시글에 대한 다건 조회 요청 

저는 최신 게시글에 대한 다건 조회 요청에 대한 응답으로 RecentPostsResponse 이런 것을 생각했습니다. 
그리고는 다음 고민이 생겼었슴다. 
> RecentPostsResponse 안에는 List<\T> 을 담고 있고 싶은데, "T" 와 "게시글 단일 요청시 응답하는 DTO" 를 분리하고 싶다.
> 이렇게 하고자 하는 이유 : 다건조회 시에 포함하고 있어야 할 정보와, 단일 조회 시에 포함하고 있어야 할 정보가 다를 수도 있다(ex-다건 조회시에 보내는 Post 에 대한 컨텐츠는 컨텐츠 전체는 보여주지는 않는다던가) 

그러고 나니 이 "T" 와 "게시글 단일 요청시 응답하는 DTO" 의 네이밍을 어떻게 할지가 고민이 되더라구요.
둘 다 어쨌거나 "단일" Post 에 대한 정보를 담고, 전달하는 객체 인데.. 

저는 이 때 결국 결론을 못 내고 그냥, PostInfo, SinglePost 이런식으로 네이밍을 했었던 거 같슴다

여러 분 이라면 어떻게 하실 것 같으신 가욥?

**Comment by HyoungUkJJang** [comment]
1장은 실무에 대한 언급은 크게 없었지만 나쁜코드에 대한 이야기가 취준할때 보다는 많이 와닿았습니다.
특정 기간에 개발을 완료를 해야하기 때문에 코드의 품질이 떨어지는 경우가 있는데 추후 리팩토링 계획을 가지려 해도 개발 해야하는 기능들이 쌓여있어 나쁜코드가 계속 쌓여가는 느낌을 받았었습니다. 
  * 리팩토링의 중요성도 이런 기간과 관련해서 중요해지지 않았을까 라는 생각도 좀 들었던 것 같아요

즉 언어적으로 제공하는 기능들을 잘 사용해서 코드를 작성하는 숙련도의 중요성을 알게되었습니다. 유명한 사람들의 깨끗한 코드의 정의를 기억하면서 코드를 작성하도록 노력하야겠습니다..!

**Comment by YHLEE9753** [comment]
1장에서 마이클 페더스가 한 말이 제일 인상깊었습니다. 
깨끗한 코드는 언제나 누군가 주의깊게 짰다는 느낌을 주고, 작성자가 이미 모든 사항을 고려하여 딱히 고칠 것이없다. 이런 코드를 짜고싶네요

추가로 코드작성보다 코드 읽는 시간이 더 많기 때문에 읽기쉬운 코드를 짜라 + 고치기 쉬운 코드를 짜라 라는 말도 인상깊었습니다.
