### ISSUE TITLE
5장 형식 맞추기

### ISSUE THREAD

**Issue by YHLEE9753** [Dev-Prison/Clean-Code#11]

**Comment by ynoolee** [comment]
1. 서로 밀접한 개념은 세로로 가깝게 위치해야 한다는 내용은 지난번에 함수 단원에서 위에서 아래로 읽히도록 작성해야 한다는 내용이 생각났습니다. 
2. 제가 지금은 책이 없는데 "수직 거리, 세로 밀집도" 부분에서 
    > protected 변수는 밀접한 개념을 다른 파일에 위치 시키게 한다.
   는 내용이 있는데, protected 변수가 왜 밀접한 개념을 다른 파일에 위치 시키게 한다는 것인지 이해를 못했습니다

전체적으로 익숙한 내용으로, 하나의 클래스 파일 내에서도 위에서 아래로 읽혀지도록 세로로 잘 배치시키고 유사한 개념들의 함수들은 가까이 위치하도록 의식하며 작성해야 겠다 는 생각이 들었습니다.
