### ISSUE TITLE
7장 오류처리

### ISSUE THREAD

**Issue by ynoolee** [Dev-Prison/Clean-Code#15]
7장의 내용을 읽고 궁금한 부분 or 느낀점을 자유롭게 적어주세요 :)

이전 PR 을 커밋 안하고 7 장을 push 했더니 5,6장 PR 에 함께 merge 되어버렸슴다....
[ch07](https://github.com/Dev-Prison/Clean-Code/blob/4ef0a07486887264b3aed73f46165fdb13debced/ynoolee/ch07_%EC%98%A4%EB%A5%98%EC%B2%98%EB%A6%AC.md) 정리 자료입니다!

**Comment by YHLEE9753** [comment]
- Checked Exception 을 사용하지 마라(OCP 위반) 가 여러 스터디를 하면서 반복되는 거 같습니다
- 감싸기 메서드나 감싸기 클래스 활용이 중요한 거 같습니다.

**Comment by HyoungUkJJang** [comment]
null을 전달, 반환하지 말라는 부분에 공감이 가고 이 부분을 잘 지켜서 팀의 규칙이나 프로젝트 규칙으로 적용하면 좋을 것 같네요 현재 실무에서 null을 어떻게하면 빠르게 리팩토링해서 없앨 수 있을까란 고민도 해볼 수 있어서 좋았습니다 :)

**Comment by ynoolee** [comment]
1. 비검사 예외를 사용해야 하는 이유와 관련해 검사예외로 인해 캡슐화가 깨지기에 OCP 도 위반한다고 말 할 수 있다는 것을 알게되었습니다
2. 외부 API 사용시 래퍼 클래스 와 커스텀 예외 클래스를 작성하여 유지보수성을 높일 수 있음을 알게 되었습니다
3. 엘레강트 오브젝트에서도 나왔던 것 처럼 예외를 분기처리에 사용할 경우 객체 내부로 감싸는 것을 생각해 봐야 하는 부분이 또 나온 것 같습니다 

전체적으로 예외처리 와 관련한 클린 코드 작성 에 대한 내용이었는데도, 객체지향 관점에서 해결해 나가는 것이 인상깊었습니다
