### ISSUE TITLE
8장 경계

### ISSUE THREAD

**Issue by ynoolee** [Dev-Prison/Clean-Code#17]
책을 읽으며 궁금했거나 공유하고 싶은 내용이 있다면 자유롭게 적어보아요

**Comment by ynoolee** [comment]
어떤 기능을 제공해야 하는 경우에는 인터페이스 형태로 정의해, 사용하는 측에서 Fake객체 를 직접 만들어 테스트가 용이하도록 만들 수 있는 내용은 어느 책에서든 자주 등장하는 것 같습니다. 
경계테스트 케이스가 뭔가 했는데 현재 내 프로젝트에서 외부 API 를 사용하는 부분만을 위한 테스트였습니다. 확실히 이런 부분만을 따로 테스트로 작성해 두면 외부 API 업데이트 시 원하는대로 그대로 동작하는지 빠르게 확인해서 새로운 버전으로 업데이트 하기 좋을 것 같네요

**Comment by HyoungUkJJang** [comment]
외부 라이브러리나 다른 팀의 기능에 요청을 해야하는 일이 종종 생기는데 그 경계에 대해서 다시한번 생각해 볼 수 있어서 좋았습니다
외부 라이브러리에 대해 테스트코드를 작성한 곳은 아직 보지는 못했지만 프로젝트 코드에 잘 녹이기 위해 학습 테스트를 적용하는 부분이 흥미롭네요 ㅎㅎ 기회가 있다면 한번 적용해보면 좋을 것 같습니다
