### ISSUE TITLE
11장 시스템

### ISSUE THREAD

**Issue by YHLEE9753** [Dev-Prison/Clean-Code#24]

**Comment by YHLEE9753** [comment]
관심사의 분리에서 POJO TDD 로의 자연스러운 연결이 인상깊었습니다. 결국 확장성을 위해 순수한 자바 비즈니스 로직을 구현하고 TDD를 적용해야 되는 거였군요!

**Comment by ynoolee** [comment]
이번 챕터는 내용이 좀 다양했는데 그 중에서도 "완벽한 초기 설계는 없으나, 확장 가능한 설계를 만들기 위해서는 관심사를 분리한 아키텍쳐를 만들어두는 것은 중요하다" 라는 내용을 추출해 볼 수 있었슴다. 하지만 AOP 도 있고 DI 컨테이너 역할도 해주는 스프링을 사용하면서도, 확장가능한 설계를 만든다는 것은 쉽지 않은 것 같습니다. 특히 어떤 도메인이 확장 가능하도록 설계하는 것 자체가 다양한 경험을 해보지 않은 이상 아직 많이 어렵다고 느꼈었습니다 

책에서 주석으로 
>'흔히 AOP 를 구현하는 기법' 과 'AOP 자체를 혼동' 한다 AOP 시스템의 진정한 가치는 시스템 동작을 간결하고 모듈화된 방식으로 명시하는 능력이다.

라는 부분이 있었는데, 최근에 AOP 는 프록시지 라고 생각하던 제가 떠올라 반성했습니다.
이번 챕터는 저에게는 내용이 쉽지 않았던 것 같습니다. 여러 번 다시 읽어 보는게 필요할 거 같습니다.

**Comment by su-pernova** [comment]
> Spring AOP 를 조금 더 찾아봤는데, 잘 정리된 글이 있어 공유합니다!

https://steady-coding.tistory.com/608
