### ISSUE TITLE
14장 점진적인 개선 (1)

### ISSUE THREAD

**Issue by YHLEE9753** [Dev-Prison/Clean-Code#33]

**Comment by ynoolee** [comment]
272쪽 까지는 약간 왜 지저분한 코드를 짜보고, 점진적 개선을 해야하는지에 대한 이유 를 말하는 부분 같았습니다. 
코드를 여러번 읽어보고 있지만, 아직 코드만을 보고 의도라던가, 어디를 개선해야하는지 확 보이지는 않아서 슬픕니다. 

저는 전에 레거시 코드에 대한 리팩토링이라는 것은 구조까지 확 개선시키는 것인 줄 알았는데, 최근에는 '구조나 시그니쳐에 최대한 적은 영향을 주면서 점진적으로 개선시키는 것' 이 중요하다고 생각이 듭니다. 

이번 장을 읽으며 레거시를 개선시킬 눈이 조금이라도 뜨였으면 좋겠다는 바람이 드네요

**Comment by su-pernova** [comment]
'잘 짜여진 코드' 는 코드에 변경을 가할 때 특히 빛을 발한다고 생각합니다.
내 의도대로 코드를 변경해야 하지만, 단순한 변경만으로 그 의도가 반영될 수 있다면 아주 잘 짜여진 코드라는 생각이 들어요.

그래서 코드를 짤 때 어떤 식으로 구조를 잡아야 할 지 막막할 때에는 미래에 어떤 변경이 가해질 수 있을까를 상상해보면서
그 변경이 쉽게 적용될 수 있도록 구조를 잡으면 조금 수월한 것 같습니다.

코드 예시가 많은 챕터라 따로 내용을 정리하기 보다는 후루룩 읽는게 더 좋은 챕터인 듯 하네요! 🤓
