### ISSUE TITLE
14장 점진적인 개선 (3)(마지막)

### ISSUE THREAD

**Issue by ynoolee** [Dev-Prison/Clean-Code#37]
책 읽으며 인상적 이었거나 공유 하고 싶은 내용 적어봅시다~

**Comment by su-pernova** [comment]
책의 `아침에 엉망으로 만든 코드를 오후에 정리하기는 어렵지 않다` 라는 말이 인상깊었습니다 ㅎ
1차 배포일까지 일단 돌아가는 코드를 짜자! 라는 생각을 한 적이 많았는데,
한바탕 개발이 끝난 다음에 리팩토링 하는 것 보다
그날 짠 코드는 바로바로 개선하는 습관을 들여야겠습니다!

**Comment by ynoolee** [comment]
처음부터 인터페이스를 분리해서 사용하려는 것은 오버 엔지니어링 같습니다. 
서비스 계층에 비즈니스 규칙을 모두 넣다보니, 책임도 모호해지고, 그에 따라 하나의 클래스에 여러 기능들이 많이 얽혀 있어 가독성이 떨어진다고 느꼈었습니다.  서비스 계층들을 여러 클래스로 분리하는 것 외에도 이런식으로 비즈니스 로직이 복잡해질 수록 살기 위해서 도메인 주도 개발을 하나 라는 생각도 들었습니다.

최근 개발자 온보딩 책을 읽을 때 기술 부채 는 "내 마음에 들지 않는 결정" 이 아닌 "팀이 지불하게 될 이자" 라는 비유가 있었는데, 나쁜 코드는 기술부채가 맞는 것 같습니다 ㅎㅎㅎ...
