### ISSUE TITLE
15장 Junit 들여다보기

### ISSUE THREAD

**Issue by ynoolee** [Dev-Prison/Clean-Code#40]
궁금하거나 새롭게 알게 된 점에 대해 자유롭게 말해봅시다~

**Comment by ynoolee** [comment]
Junit 에 대한 내용인 줄 알았는데, 초기에 작성된 모듈 하나를 좀 더 개선시켜나가는 과정에 대한 이야기 였습니다 
14장도 계속해서 점진적으로 리팩토링 해 나갔던 내용이라 , 15 장 내용에서 크게 새로웠던 것은 없었던 것 같아요. 이런 부분까지도 개선해 나갈 수 있구나 하는 내용은 신기했습니다. 
예를들어, 함수 사이의 시간적 결합이 존재할 때, 두 개의 별개의 함수가 존재하는 한 항상 잘못 불려질 위험이 존재하는데, 아예 A 함수, B 함수를 C 함수에다 넣을 때 B 함수는 따로 두지 않고 그 로직만을 C 에다가 두는 방법이 있구나 ~ 싶었습니다. 
시간적 결합이 존재하는 함수가 3개 이상이 된다면..설계가 잘못된 것이려나요

**Comment by su-pernova** [comment]
형욱님 고생많으셨습니다~! 🙌
