### ISSUE TITLE
16장 SerialDate 리팩터링

### ISSUE THREAD

**Issue by su-pernova** [Dev-Prison/Clean-Code#42]
16장 SerialDate 리팩터링

**Comment by YHLEE9753** [comment]
리팩토링에 대한 명확한 기준이 있다면 쉽게 리팩터링할수있을거 같습니다
- 주석, 네이밍 고민, 추상화 수준, 책임의 분배, 중복 제거, 버그 수정, 정적 변수 메서드 관리...

**Comment by su-pernova** [comment]
레거시 코드를 회사에서 종종 받는데, 어떻게 리팩터링을 시작해야 할지 막막했던 적이 많은데요
책에서 소개하는 요소들 위주로 살펴본다면 조금 더 쉽게 작업할 수 있을 것 같습니다!
