### ISSUE TITLE
17장 냄새와 휴리스틱(1)

### ISSUE THREAD

**Issue by YHLEE9753** [Dev-Prison/Clean-Code#45]
C1 ~ G25

**Comment by HyoungUkJJang** [comment]
이번 장은 간략하게 팁들 위주로 나와있어서 읽기 편했던 것 같습니다 :) 
와닿는 부분들도 있고 고민할 수 있는 포인트들이 몇개 있어서 좋았습니다 ~!

**Comment by YHLEE9753** [comment]
코드 가이드북 느낌입니다! 책전체를 간략하게 정리해주는 느낌이어서 좋은거같습니다!

**Comment by su-pernova** [comment]
처치 곤란한 `주석 처리된 코드` 를 만난 적이 종종 있었는데, 과감하게 지워버리면 될 것 같습니다!
한번만 호출되는 함수는 무조건 `static` 으로 선언하는 것이 성능에 좋지 않을까? 라고 생각했는데, 재정의 가능성을 생각 못했네요.
형욱님 고생 많으셨습니다~! 🙌
