### ISSUE TITLE
17장 냄새와 휴리스틱(2)

### ISSUE THREAD

**Issue by su-pernova** [Dev-Prison/Clean-Code#47]

**Comment by ynoolee** [comment]
G26 에서 통화 관련해 부동소수점은 사용하지 않는게 좋다고 생각은 했었는데, 그 외의 방법으로는 BigDecimal 밖에 떠오르지 않아 검색해보니 [이런거](https://www.baeldung.com/java-money-and-currency)도 있네요!

항상 같은 추상화레벨을 갖는 코드를 갖는 것 만으로도 좋은 것 같은데 그게 제일 어려운 것 같습니다.

**Comment by YHLEE9753** [comment]
G31 에서 시간적인 결합을 연결소자를 통해 강제하는게 흥미로웠습니다
코드에 단순히 함수 나열이 많은데 코드는 좀 복잡해질수있지만 시간적인 순서를 지킬수 있다는 점에서 새로운 방법을 배워갑니다!
