### ISSUE TITLE
3장 함수

### ISSUE THREAD

**Issue by HyoungUkJJang** [Dev-Prison/Clean-Code#5]
3장의 내용을 읽고 궁금한 부분 or 느낀점을 자유롭게 적어주세요 :)

**Comment by YHLEE9753** [comment]
- 함수의 추상화 수준을 통해 코드를 분리하라는 말이 인상깊었습니다
- switch 문의 경우 추상 팩토리와 다형성으로 최초 생성에만 switch 를 사용하거 이외에는 파생 클래스의 함수실행이 인상깊었습니다
- 이항 함수를 단항 함수로 바꾸는 방법이 신기했는데 그중 클래스 구성원 변수로 만들어 인수를 줄이는 방법은 유용해 보이네요

**Comment by ynoolee** [comment]
책 읽으면서, 말이 애매한? 왜 타이틀을 나누어서 설명하지 싶은 내용도 한번 적어보겠습니다
계속해서 추가해 나갈게요~

1. (책 내용 구성에 대한 질문 ) 45page 에서 "함수 내 섹션" 이 그 바로 위 문단에서 "의미 있는 이름으로 다른 함수를 추출 할 수 있으면 여러 작업을 하는 함수이다" 와 거의 같은 것으로 이해되는데 다른 분들은 어떠신지 궁금합니다. 
2. (느낀점) enum 을 switch 문에서 사용하는 코드가 생기면 항상 고민하게 되는 문제는 여러 책에서 등장하네요. 근데 저는 Employee 같은 그 공동의 추상클래스를 뽑아내는게 정말 어렵다고 느껴집니다 
3. ( 느낀 점 ) 출력인수 라는 단어를 처음 알았습니다. c 언어를 할 때 주로 이런 방식을 많이 사용했던 것 같은데요.. 최근까지도 이런 코드를 작성했던 것 같습니다;; 출력 인수가 생기는 경우라면 클래스를 선언하는 것을 고려해 봐야 할 거 같네요 
4. (느낀점) 용훈님 처럼 구성원 변수로 만들어 인수를 줄이는 부분이 인상깊었습니다. 이제까지  함수인수를 줄이 기 위해서 인수 객체를 만드는 방식만 을 생각해왔었슴다. 그런데 이렇게  인수 하나를 객체 상태로 갖고 있고, 이렇게 객체가 갖고 있는 상태에 대한 행위로 변경할 수 있다는 방식도 있군요

**Comment by HyoungUkJJang** [comment]
느낀점
- 작게 만들어야 하는 부분과 부수 효과를 일으키지 않는 부분이 많이 공감이 되었습니다.
- 여러가지 이름으로 설명이 되는 함수는 다른 함수로 추출하는 부분도 공감이 가고 인상 깊었지만, 단 한 곳에서만 일어나는 책임이라면 함수로 추출을 해야하는가? 라는 고민은 되는 것 같습니다.

연우님 질문
- 네 저도 동일하게 이해를 하고 책을 읽었습니다 :)
