### ISSUE TITLE
4장 주석

### ISSUE THREAD

**Issue by ynoolee** [Dev-Prison/Clean-Code#8]
책 내용, 책을 읽으며 느낀 점, 궁금한 점 등에 대해 자유롭게 남겨주세요~

**Comment by ynoolee** [comment]
- 리팩토링을 통해서 삭제할 수 있는 주석이 많으니, 주석을 달 때면 자신의 표현력의 한계에 통탄하라는 말이 뼈 때리는 거 같았습니다 
- **(다른 분들의 생각이 궁금한 부분! )** 하지만  수학적 연산과 관련된 부분은 오히려 이를 나타내는 변수명을 다 추출해서 나타내다 보면 코드가 너무 장황해질 것 같습니다. 이런 부분은 주석을 사용하는게 더 좋을 부분 같다는 생각이 들었는데 다른 분들은 어떻게 생각하시나요?
- TODO 주석을 남기는것이 “ 나쁜 코드를 남기는 것에 대한 핑계가 되어선 안된다" 는 말이 굉장히 찔렸습니다
- 최근에는 TODO 로 다른 부분이 작성하신 코드에 대한 오류를 적고 이부분을 개선해달라고 사용한적이 있는데, 이렇게 써두 되나? 싶었는데 그런 사용은 좋은 주석이라고 말해주는 내용도 있어 안심했슴다..ㅎㅎ;
- **( 궁금한 부분 )** Junit 테스트 작성시 @DisplayName 도 주석 같은 부분 일까요? 🤔

이번 내용은 가볍게 읽으면서도, 이제까지 제일 덜 주의 하던 부분 이라 앞으로 코드 작성에서 많이 주의해야겠다고 생각했슴다

**Comment by YHLEE9753** [comment]
주석에 대해 한번 더 생각해볼 수 있는 계기가 되어 좋았던거 같습니다
- 수학적 연산과 관련되어서는 정도에 따라서는 주석을 활용해도 좋을 거 같습니다
- DisplayName 은 주석보다는 제목 느낌이라 테스트 실행시 한번에 파악하기 좋으니 장려해도 좋을거 같습니다 ㅎㅎ

**Comment by HyoungUkJJang** [comment]
이번 4장을 읽으면서 개인 프로젝트를 진행했을 때 자바독을 상세하게 적어서 진행한 적이 있었는데 오히려 상세한 주석이 코드의 품질을 많이 저하시킬 수 있다는 피드백을 받은 기억이 나네요 ㅎㅎ 
지속적으로 코드가 유지보수됨에 따라 코드가 변경되면서 주석도 함께 변경이 되어야 하는데 그 규칙이 잘 지켜지지 않기 때문에 오히려 복잡성을 증가시키고 메서드 이름을 의미있게 짓는게 훨씬 낫다라는 피드백을 받았었습니다.

저도 용훈님 말씀대로 수학적 연산이나 이해하기 어려운 로직들에 대해서는 주석을 활용해도 좋을 것 같네요 ! DisplayName도 동의합니다 !

실무에서도 todo 주석을 많이 보게되는데 너무 todo를 남발해서는 안된다고 생각이 들었습니다. 이번에 한번 todo 주석들을 정리할 생각을 가지고 있었는데 마침 내용이 나와서 재밌게 읽을 수 있었습니다 ~!
